version: '3.8'

services:
  app:
    container_name: reverse-proxy
    image: dleclercpro/reverse-proxy:latest
    restart: no
    ports:
      - 443:443 # HTTPS
      - 80:80   # HTTP
    volumes:
      - letsencrypt:/etc/letsencrypt
    env_file:
      - .env

volumes:
  letsencrypt: