version: '3.8'

services:
  app:
    container_name: ssl-reverse-proxy
    image: dleclercpro/ssl-reverse-proxy:v1.1.0
    restart: no
    ports:
      - 443:443 # HTTPS
      - 80:80   # HTTP
    volumes:
      - letsencrypt:/etc/letsencrypt
    env_file:
      - .env

volumes:
  letsencrypt: